#https://github.com/mariahlamb/proxy-sub
name: generate_nodes

on:
  push:
    paths:
      - 'sub/**'
  workflow_dispatch:

jobs:
  generate-nodes-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Nodes
        run: |
          python generate_nodes.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add all_nodes.txt
          git commit -m "Update Nodes List [skip ci]" || echo "No changes to commit"
          git push
